In [ ]:
import pandas as pd
renewable_sources=["Solar","Wind","Hydropower","Geothermal","Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}


In [ ]:
#create series
renewable_sources=pd.Series(renewable_sources)
renewable_sources

0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object

In [ ]:
#create dataframe
projects_df=pd.DataFrame(data)
projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
projects_df.head(3)

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [ ]:
projects_df.tail(3)

Project  Technology  Capacity (MW)  Cost (Million $)  \
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
second_and_third_rows=projects_df[1:3]
print(second_and_third_rows)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [ ]:
projects_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 368.0+ bytes


In [ ]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

from matplotlib import pyplot as plt
_df_0['Capacity (MW)'].plot(kind='hist', bins=20, title='Capacity (MW)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Cost (Million $)'].plot(kind='hist', bins=20, title='Cost (Million $)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Completion Year'].plot(kind='hist', bins=20, title='Completion Year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='Capacity (MW)', y='Cost (Million $)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Cost (Million $)', y='Completion Year', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5['Capacity (MW)'].plot(kind='line', figsize=(8, 4), title='Capacity (MW)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['Cost (Million $)'].plot(kind='line', figsize=(8, 4), title='Cost (Million $)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['Completion Year'].plot(kind='line', figsize=(8, 4), title='Completion Year')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
high_capacity_projects=projects_df[projects_df["Capacity (MW)"]>100]
print(high_capacity_projects)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [ ]:
projects_df['Cost per MW'] = projects_df['Cost (Million $)'] / projects_df['Capacity (MW)']
projects_df

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000

In [ ]:
total_capacity=projects_df['Capacity (MW)'].sum()
print(total_capacity)
total_cost=projects_df['Cost (Million $)'].sum()
print(total_cost)


800
1300


In [ ]:
grouped_data = projects_df.groupby('Technology')['Capacity (MW)'].sum()
print(grouped_data)

grouped_data1 = projects_df.groupby('Technology')['Cost (Million $)'].sum()
print(grouped_data1)

Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64
Technology
Geothermal    250
Hydropower    350
Solar         300
Wind          400
Name: Cost (Million $), dtype: int64


In [ ]:
import numpy as np
oda=np.array([1,2,3,4,5])
print(oda)

[1 2 3 4 5]


In [ ]:
two_d_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
one_d_array=np.array([10,20,30,40,50])
print(one_d_array)
print(("Array: ",one_d_array))
print("Shape: ",one_d_array.shape)
print("Size: ",one_d_array.size)
print("Data Type: ",one_d_array.dtype)
print("Item Size: ",one_d_array.itemsize)
print(" no. of Dimensions: ",one_d_array.ndim)

[10 20 30 40 50]
('Array: ', array([10, 20, 30, 40, 50]))
Shape:  (5,)
Size:  5
Data Type:  int64
Item Size:  8
 no. of Dimensions:  1


In [ ]:
np.random.random(4)

array([0.94362047, 0.45854282, 0.79264827, 0.57990257])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
array=np.full((3,3),10)
print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
identity_array=np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
array_with_arrange=np.arange(0,10,2)
print(array_with_arrange)

[0 2 4 6 8]


In [ ]:
array2=np.arange(5,15,2)
print(array2)

[ 5  7  9 11 13]


In [ ]:
linspace_array=np.linspace(5,10,3)
print(linspace_array)

[ 5.   7.5 10. ]


In [ ]:
linspace_array2=np.linspace(2.0,3.0,num=5,endpoint=False)
print(linspace_array2)

[2.  2.2 2.4 2.6 2.8]


In [ ]:
#indexing and slicing
data=np.array([1,3,5,7,9])
print(data[0])
print(data[1])

1
3


In [ ]:
num_data=np.array([11,22,33,44,55,66,77,88,99])
print(num_data[:])
print(num_data[::1])
print(num_data[::2])
print(num_data[::-1])


[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]
[11 33 55 77 99]
[99 88 77 66 55 44 33 22 11]


In [ ]:
def is_palindrome(text):
  processed_text = text.lower().replace(" ", "")  # ignore case and spaces
  return processed_text == processed_text[::-1]  # compare string to its reverse
# Get input from the user
string = input("Enter a string: ")
# Check if the string is a palindrome
if is_palindrome(string):
  print(f"'{string}' is a palindrome.")
else:
  print(f"'{string}' is not a palindrome.")

Enter a string: nun
'nun' is a palindrome.


In [ ]:
#array manipulation
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
myarray=np.array([[1,2,3],[4,5,6]])
print(myarray.flatten())
print(myarray.flatten('F'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [ ]:
import numpy as np


data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5])


mean = np.mean(data)
print("Mean:", mean)


from scipy import stats
mode = stats.mode(data)
print("Mode:", mode[0])

median = np.median(data)
print("Median:", median)

std_dev = np.std(data)
print("Standard Deviation:", std_dev)

Mean: 3.0
Mode: 3
Median: 3.0
Standard Deviation: 1.1547005383792515


In [ ]:
energy_consumption=np.array([1200,3400,2900,1800,2500])
print("energy_consumption : ",energy_consumption)

energy_consumption :  [1200 3400 2900 1800 2500]


In [ ]:
import numpy as np
from scipy import stats

energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

mean = np.mean(energy_consumption)
print("Mean:", mean)

mode = stats.mode(energy_consumption)
print("Mode:",mode[0])


median = np.median(energy_consumption)
print("Median:", median)


std_dev = np.std(energy_consumption)
print("Standard Deviation:", std_dev)

Mean: 2360.0
Mode: 1200
Median: 2500.0
Standard Deviation: 781.2809993849844
